name: root_project
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.1.0

dev_dependencies:
  melos: ^3.1.1
  freezed: ^2.1.1

flutter:
  uses-material-design: true

#  fonts:
#    - family: Gotham Extra Bold
#      fonts:
#        - asset: fonts/Gotham-Black.otf
#          weight: 500
#    - family: Gotham Light
#      fonts:
#        - asset: fonts/Gotham-Light.otf
#          weight: 500
#    - family: Gotham
#      fonts:
#        - asset: fonts/Gotham-Medium.otf
#          weight: 500
